let warframes = [
{nombre:"Ash",descripcion:"Asesino sigiloso.",estadisticas:{salud:450,escudos:300,armadura:150,energia:100},habilidades:["Shuriken","Smoke Screen","Teleport","Blade Storm"]},
{nombre:"Atlas",descripcion:"Controla la tierra.",estadisticas:{salud:450,escudos:300,armadura:450,energia:100},habilidades:["Landslide","Tectonics","Petrify","Rumblers"]},
{nombre:"Banshee",descripcion:"Manipula el sonido.",estadisticas:{salud:300,escudos:300,armadura:100,energia:150},habilidades:["Sonic Boom","Sonar","Silence","Sound Quake"]},
{nombre:"Baruuk",descripcion:"Monje pacifista.",estadisticas:{salud:375,escudos:300,armadura:225,energia:200},habilidades:["Elude","Lull","Desolate Hands","Serene Storm"]},
{nombre:"Caliban",descripcion:"Híbrido Sentient.",estadisticas:{salud:375,escudos:450,armadura:275,energia:175},habilidades:["Razor Gyre","Sentient Wrath","Lethal Progeny","Fusion Strike"]},
{nombre:"Chroma",descripcion:"Maestro elemental.",estadisticas:{salud:300,escudos:300,armadura:350,energia:100},habilidades:["Spectral Scream","Elemental Ward","Vex Armor","Effigy"]},
{nombre:"Citrine",descripcion:"Cristales curativos.",estadisticas:{salud:450,escudos:300,armadura:350,energia:175},habilidades:["Fractured Blast","Preserving Shell","Prismatic Gem","Crystallize"]},
{nombre:"Cyte-09",descripcion:"Warframe táctico.",estadisticas:{salud:400,escudos:300,armadura:200,energia:150},habilidades:["Ability 1","Ability 2","Ability 3","Ability 4"]},
{nombre:"Dagath",descripcion:"Entidad espectral.",estadisticas:{salud:400,escudos:300,armadura:250,energia:150},habilidades:["Wyrd Scythes","Grave Spirit","Rakhali’s Cavalry","Doom"]},
{nombre:"Dante",descripcion:"Mago arcano.",estadisticas:{salud:350,escudos:350,armadura:200,energia:200},habilidades:["Wordwarden","Tragedy","Triumph","Final Verse"]},
{nombre:"Ember",descripcion:"Controla el fuego.",estadisticas:{salud:375,escudos:300,armadura:100,energia:150},habilidades:["Fireball","Immolation","Fire Blast","Inferno"]},
{nombre:"Equinox",descripcion:"Dualidad día/noche.",estadisticas:{salud:375,escudos:300,armadura:150,energia:150},habilidades:["Metamorphosis","Rest & Rage","Pacify & Provoke","Mend & Maim"]},
{nombre:"Excalibur",descripcion:"Equilibrado.",estadisticas:{salud:300,escudos:300,armadura:225,energia:100},habilidades:["Slash Dash","Radial Blind","Radial Javelin","Exalted Blade"]},
{nombre:"Frost",descripcion:"Controla el hielo.",estadisticas:{salud:300,escudos:450,armadura:300,energia:150},habilidades:["Freeze","Ice Wave","Snow Globe","Avalanche"]},
{nombre:"Gara",descripcion:"Vidrio viviente.",estadisticas:{salud:300,escudos:300,armadura:150,energia:150},habilidades:["Shattered Lash","Splinter Storm","Mass Vitrify","Vitrify"]},
{nombre:"Garuda",descripcion:"Sangre y sacrificio.",estadisticas:{salud:450,escudos:300,armadura:300,energia:150},habilidades:["Dread Mirror","Blood Altar","Bloodletting","Seeking Talons"]},
{nombre:"Gauss",descripcion:"Velocidad extrema.",estadisticas:{salud:300,escudos:300,armadura:150,energia:200},habilidades:["Mach Rush","Kinetic Plating","Thermal Sunder","Redline"]},
{nombre:"Grendel",descripcion:"Devora enemigos.",estadisticas:{salud:650,escudos:300,armadura:250,energia:150},habilidades:["Feast","Nourish","Regurgitate","Pulverize"]},
{nombre:"Gyre",descripcion:"Electricidad.",estadisticas:{salud:350,escudos:450,armadura:100,energia:175},habilidades:["Arcsphere","Coil Horizon","Cathode Grace","Rotorswell"]},
{nombre:"Harrow",descripcion:"Sacerdote.",estadisticas:{salud:300,escudos:450,armadura:225,energia:150},habilidades:["Condemn","Penance","Thurible","Covenant"]},
{nombre:"Hildryn",descripcion:"Usa escudos.",estadisticas:{salud:300,escudos:1200,armadura:300,energia:0},habilidades:["Balefire","Pillage","Haven","Aegis Storm"]},
{nombre:"Hydroid",descripcion:"Control acuático.",estadisticas:{salud:375,escudos:300,armadura:250,energia:150},habilidades:["Tempest Barrage","Tidal Surge","Undertow","Tentacle Swarm"]},
{nombre:"Inaros",descripcion:"Resistencia extrema.",estadisticas:{salud:2200,escudos:0,armadura:225,energia:100},habilidades:["Desiccation","Devour","Sandstorm","Scarab Swarm"]},
{nombre:"Ivara",descripcion:"Cazadora.",estadisticas:{salud:225,escudos:300,armadura:100,energia:225},habilidades:["Quiver","Navigator","Prowl","Artemis Bow"]},
{nombre:"Jade",descripcion:"Warframe celestial.",estadisticas:{salud:400,escudos:400,armadura:200,energia:175},habilidades:["Ability 1","Ability 2","Ability 3","Ability 4"]},
{nombre:"Khora",descripcion:"Domina cadenas.",estadisticas:{salud:375,escudos:300,armadura:275,energia:175},habilidades:["Whipclaw","Ensnare","Venari","Strangledome"]},
{nombre:"Koumei",descripcion:"Warframe místico.",estadisticas:{salud:400,escudos:350,armadura:200,energia:175},habilidades:["Ability 1","Ability 2","Ability 3","Ability 4"]},
{nombre:"Kullervo",descripcion:"Guerrero castigado.",estadisticas:{salud:500,escudos:300,armadura:300,energia:150},habilidades:["Wrathful Advance","Collective Curse","Recompense","Storm of Ukko"]},
{nombre:"Lavos",descripcion:"Alquimia.",estadisticas:{salud:450,escudos:300,armadura:300,energia:0},habilidades:["Ophidian Bite","Vial Rush","Transmutation Probe","Catalyze"]},
{nombre:"Limbo",descripcion:"Control dimensional.",estadisticas:{salud:300,escudos:450,armadura:100,energia:200},habilidades:["Banish","Stasis","Rift Surge","Cataclysm"]},
{nombre:"Loki",descripcion:"Engaño.",estadisticas:{salud:225,escudos:300,armadura:100,energia:150},habilidades:["Decoy","Invisibility","Switch Teleport","Radial Disarm"]},
{nombre:"Mag",descripcion:"Magnetismo.",estadisticas:{salud:300,escudos:450,armadura:100,energia:150},habilidades:["Pull","Magnetize","Polarize","Crush"]},
{nombre:"Mesa",descripcion:"Pistolera.",estadisticas:{salud:375,escudos:300,armadura:100,energia:150},habilidades:["Ballistic Battery","Shooting Gallery","Shatter Shield","Peacemaker"]},
{nombre:"Mirage",descripcion:"Ilusión.",estadisticas:{salud:300,escudos:300,armadura:100,energia:150},habilidades:["Hall of Mirrors","Sleight of Hand","Eclipse","Prism"]},
{nombre:"Nekros",descripcion:"Nigromante.",estadisticas:{salud:375,escudos:300,armadura:150,energia:150},habilidades:["Soul Punch","Terrify","Desecrate","Shadows of the Dead"]},
{nombre:"Nezha",descripcion:"Fuego veloz.",estadisticas:{salud:375,escudos:300,armadura:175,energia:150},habilidades:["Fire Walker","Blazing Chakram","Warding Halo","Divine Spears"]},
{nombre:"Nidus",descripcion:"Infestación.",estadisticas:{salud:525,escudos:0,armadura:300,energia:150},habilidades:["Virulence","Larva","Parasitic Link","Ravenous"]},
{nombre:"Nokko",descripcion:"Warframe experimental de energía oscura.",estadisticas:{salud:400,escudos:300,armadura:250,energia:175},habilidades:["Umbra Pulse","Void Chain","Nightfall","Abyss Core"]},
{nombre:"Nova",descripcion:"Antimateria.",estadisticas:{salud:300,escudos:300,armadura:100,energia:150},habilidades:["Null Star","Antimatter Drop","Worm Hole","Molecular Prime"]},
{nombre:"Nyx",descripcion:"Control mental.",estadisticas:{salud:300,escudos:450,armadura:100,energia:150},habilidades:["Mind Control","Psychic Bolts","Chaos","Absorb"]},
{nombre:"Oberon",descripcion:"Paladín.",estadisticas:{salud:375,escudos:300,armadura:150,energia:150},habilidades:["Smite","Hallowed Ground","Renewal","Reckoning"]},
{nombre:"Octavia",descripcion:"Música.",estadisticas:{salud:300,escudos:300,armadura:150,energia:150},habilidades:["Mallet","Resonator","Metronome","Amp"]},
{nombre:"Oraxia",descripcion:"Manipuladora del tiempo y la mente.",estadisticas:{salud:350,escudos:400,armadura:150,energia:200},habilidades:["Mind Fracture","Temporal Shift","Psychic Cage","Eternal Loop"]},
{nombre:"Protea",descripcion:"Tecnología.",estadisticas:{salud:350,escudos:450,armadura:125,energia:175},habilidades:["Grenade Fan","Blaze Artillery","Dispensary","Temporal Anchor"]},
{nombre:"Qorvex",descripcion:"Radiación.",estadisticas:{salud:500,escudos:300,armadura:400,energia:150},habilidades:["Ability 1","Ability 2","Ability 3","Ability 4"]},
{nombre:"Revenant",descripcion:"Eidolon.",estadisticas:{salud:375,escudos:300,armadura:150,energia:150},habilidades:["Enthrall","Mesmer Skin","Reave","Danse Macabre"]},
{nombre:"Rhino",descripcion:"Tanque.",estadisticas:{salud:450,escudos:450,armadura:275,energia:100},habilidades:["Rhino Charge","Iron Skin","Roar","Rhino Stomp"]},
{nombre:"Saryn",descripcion:"Tóxica.",estadisticas:{salud:375,escudos:300,armadura:225,energia:150},habilidades:["Spores","Molt","Toxic Lash","Miasma"]},
{nombre:"Sevagoth",descripcion:"Sombra.",estadisticas:{salud:375,escudos:300,armadura:175,energia:150},habilidades:["Reap","Sow","Gloom","Exalted Shadow"]},
{nombre:"Styanax",descripcion:"Guerrero.",estadisticas:{salud:450,escudos:300,armadura:300,energia:150},habilidades:["Axios Javelin","Tharros Strike","Rally Point","Final Stand"]},
{nombre:"Temple",descripcion:"Guardián imparable de hierro.",estadisticas:{salud:600,escudos:300,armadura:500,energia:100},habilidades:["Iron March","Bulwark","Hammerfall","Fortress"]},
{nombre:"Titania",descripcion:"Hada.",estadisticas:{salud:300,escudos:300,armadura:125,energia:200},habilidades:["Spellbind","Tribute","Lantern","Razorwing"]},
{nombre:"Trinity",descripcion:"Soporte.",estadisticas:{salud:300,escudos:450,armadura:100,energia:150},habilidades:["Well of Life","Energy Vampire","Link","Blessing"]},
{nombre:"Uriel",descripcion:"Warframe celestial de soporte.",estadisticas:{salud:375,escudos:450,armadura:200,energia:225},habilidades:["Divine Light","Sanctuary","Judgment","Ascension"]},
{nombre:"Valkyr",descripcion:"Furia.",estadisticas:{salud:600,escudos:150,armadura:600,energia:100},habilidades:["Rip Line","Warcry","Paralysis","Hysteria"]},
{nombre:"Vauban",descripcion:"Trampas.",estadisticas:{salud:300,escudos:300,armadura:100,energia:150},habilidades:["Tesla Nervos","Minelayer","Photon Strike","Bastille"]},
{nombre:"Volt",descripcion:"Electricidad.",estadisticas:{salud:300,escudos:450,armadura:100,energia:150},habilidades:["Shock","Speed","Electric Shield","Discharge"]},
{nombre:"Voruna",descripcion:"Cazadora lupina.",estadisticas:{salud:400,escudos:300,armadura:200,energia:175},habilidades:["Shroud of Dynar","Fangs of Raksh","Lycath's Hunt","Ulfrun's Descent"]},
{nombre:"Wisp",descripcion:"Éter.",estadisticas:{salud:300,escudos:300,armadura:150,energia:300},habilidades:["Reservoirs","Wil-O-Wisp","Breach Surge","Sol Gate"]},
{nombre:"Wukong",descripcion:"Rey mono.",estadisticas:{salud:450,escudos:300,armadura:275,energia:150},habilidades:["Celestial Twin","Cloud Walker","Defy","Primal Fury"]},
{nombre:"Xaku",descripcion:"Vacío.",estadisticas:{salud:300,escudos:300,armadura:125,energia:200},habilidades:["Xata's Whisper","Grasp of Lohk","The Lost","The Vast Untime"]},
{nombre:"Yareli",descripcion:"Acuática.",estadisticas:{salud:300,escudos:450,armadura:100,energia:200},habilidades:["Sea Snares","Merulina","Aquablades","Riptide"]},
{nombre:"Zephyr",descripcion:"Viento.",estadisticas:{salud:375,escudos:300,armadura:150,energia:150},habilidades:["Tail Wind","Airburst","Turbulence","Tornado"]}
]